version: 2.1
orbs:
  k8s: circleci/kubernetes@0.7.0
  slack: circleci/slack@3.4.2
commands:
  
jobs:
  not_interactive:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - run:
          name: "Publish to cloudflare pages (staging)"
          command: |
            npm i cloudflare@2.0.19
            mkdir public
            cd public
            echo "Hello not interactive" >> index.html
            npx wrangler pages publish . --project-name=interactive-metrics --branch=not
  not_interactive:
    docker:
      - image: cimg/node:18.4.0
    steps:
      - run:
          name: "Publish to cloudflare pages (staging)"
          command: |
            npm i cloudflare@2.0.21
            mkdir public
            cd public
            echo "Hello interactive" >> index.html
            npx wrangler pages publish . --project-name=interactive-metrics --branch=main
 
workflows:
  release:
    jobs:
      - not_interactive:
          filters:
            branches:
              only: /^main$/
      - interactive:
          filters:
            branches:
              only: /^main$/
